version: "3.7"

services:
  mojaloop-testing-toolkit:
    image: mojaloop-testing-toolkit:local
    env_file: ./local.env
    build:
      context: .
      target: builder
    container_name: mojaloop-testing-toolkit
    ports:
      - "5000:5000"
      - "5050:5050"
    command:
      - sh
      - -c
      - "npm start"
  mojaloop-testing-toolkit-postman:
    image: mojaloop-testing-toolkit-postman:local
    build:
      context: .
      dockerfile: Dockerfile-newman
    container_name: mojaloop-testing-toolkit-postman
    depends_on:
      - mojaloop-testing-toolkit
